name: wot_3p1_umerc2025
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.16
  - aiosignal=1.3.2
  - attrdict=2.0.1
  - attrs=25.3.0
  - aws-c-auth=0.8.7
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.1
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.5
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.1
  - aws-sdk-cpp=1.11.510
  - blinker=1.9.0
  - bokeh=3.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - cachetools=5.5.2
  - capytaine=2.2.1
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - cmocean=4.0.3
  - colorama=0.4.6
  - colorspacious=1.1.2
  - contourpy=1.3.2
  - crc32c=2.7.1
  - cryptography=44.0.2
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2025.3.0
  - dask-core=2025.3.0
  - decorator=5.2.1
  - deprecated=1.2.18
  - distributed=2025.3.0
  - donfig=0.8.1.post1
  - fonttools=4.57.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2025.3.2
  - gcsfs=2025.3.2
  - google-api-core=2.24.2
  - google-auth=2.39.0
  - google-auth-oauthlib=1.2.1
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.1.0
  - google-crc32c=1.7.1
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.70.0
  - grpcio=1.71.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - intel-openmp=2024.2.1
  - jinja2=3.1.6
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libdeflate=1.23
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflang=5.0.0
  - libgcc=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libparquet=19.0.1
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-meta=5.0.0
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - mdurl=0.1.2
  - mkl=2024.2.2
  - msgpack-python=1.1.0
  - multidict=6.3.2
  - munkres=1.1.4
  - narwhals=1.35.0
  - numba=0.61.2
  - numcodecs=0.15.1
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.5.3
  - openmp=5.0.0
  - openssl=3.5.0
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - partd=1.4.2
  - pillow=11.1.0
  - pip=25.0.1
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyopenssl=25.0.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.11.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - qhull=2020.2
  - re2=2024.07.02
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rich=14.0.0
  - rsa=4.9.1
  - scipy=1.15.2
  - setuptools=78.1.0
  - six=1.17.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - tbb=2021.13.0
  - tblib=3.1.0
  - tk=8.6.13
  - toolz=1.0.0
  - tornado=6.4.2
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wavespectra=4.4.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.2
  - xarray=2025.3.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.1.0
  - yaml=0.2.5
  - yarl=1.18.3
  - zarr=3.0.6
  - zict=3.0.0
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - alabaster==1.0.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - autograd==1.7.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - cftime==1.6.4.post1
      - comm==0.2.2
      - debugpy==1.8.14
      - defusedxml==0.7.1
      - docutils==0.21.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - gmsh==4.13.1
      - h11==0.14.0
      - httpcore==1.0.8
      - httpx==0.28.1
      - imageio==2.37.0
      - imagesize==1.4.1
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==9.1.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - latexcodec==3.0.0
      - matplotlib-inline==0.1.7
      - meshio==5.3.5
      - mistune==3.1.3
      - ml-dtypes==0.5.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nbsphinx==0.9.7
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - notebook==7.4.0
      - notebook-shim==0.2.4
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandoc==2.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - platformdirs==4.3.7
      - pluggy==1.5.0
      - plumbum==1.9.0
      - ply==3.11
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - pure-eval==0.2.3
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pygifsicle==1.1.0
      - pygmsh==7.1.17
      - pytest==8.3.5
      - python-json-logger==3.3.0
      - pywin32==310
      - pywinpty==2.0.15
      - pyzmq==26.4.0
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.3
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - vtk==9.4.2
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wecopttool==3.1.0
      - widgetsnbextension==4.0.14
